//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fosol.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Multilingual {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Multilingual() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fosol.Core.Resources.Multilingual", typeof(Multilingual).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be a compatible type..
        /// </summary>
        internal static string Collections_ResizeList_Add_CompatibleType {
            get {
                return ResourceManager.GetString("Collections_ResizeList_Add_CompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must not be a multi-dimensional array..
        /// </summary>
        internal static string Collections_ResizeList_CopyTo {
            get {
                return ResourceManager.GetString("Collections_ResizeList_CopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumerator index position is invalid..
        /// </summary>
        internal static string Collections_ResizeList_Enumerator_Current {
            get {
                return ResourceManager.GetString("Collections_ResizeList_Enumerator_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumerator version has been changed and can no longer enumerate..
        /// </summary>
        internal static string Collections_ResizeList_Enumerator_MoveNext {
            get {
                return ResourceManager.GetString("Collections_ResizeList_Enumerator_MoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumerator version has been changed and can not be reset..
        /// </summary>
        internal static string Collections_ResizeList_Enumerator_Reset {
            get {
                return ResourceManager.GetString("Collections_ResizeList_Enumerator_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramter &quot;{0}&quot; must be a compatible type..
        /// </summary>
        internal static string Collections_ResizeList_Insert_CompatibleType {
            get {
                return ResourceManager.GetString("Collections_ResizeList_Insert_CompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be a compatible type..
        /// </summary>
        internal static string Collections_ResizeList_Property_CompatibleType {
            get {
                return ResourceManager.GetString("Collections_ResizeList_Property_CompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}.CanWrite&quot; must be true..
        /// </summary>
        internal static string Extensions_Bytes_ByteExtensions_ToStream_CanWrite {
            get {
                return ResourceManager.GetString("Extensions_Bytes_ByteExtensions_ToStream_CanWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}.CanRead&quot; must be true..
        /// </summary>
        internal static string Extensions_Streams_StreamExtensions_CopyTo_CanRead {
            get {
                return ResourceManager.GetString("Extensions_Streams_StreamExtensions_CopyTo_CanRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}.CanWrite&quot; must be true..
        /// </summary>
        internal static string Extensions_Streams_StreamExtensions_CopyTo_CanWrite {
            get {
                return ResourceManager.GetString("Extensions_Streams_StreamExtensions_CopyTo_CanWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}.CanRead&quot; must be true..
        /// </summary>
        internal static string Extensions_Streams_StreamExtensions_SaveToFile_CanRead {
            get {
                return ResourceManager.GetString("Extensions_Streams_StreamExtensions_SaveToFile_CanRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}.CanRead&quot; must be true..
        /// </summary>
        internal static string Extensions_Streams_StreamExtensions_WriteToString_CanRead {
            get {
                return ResourceManager.GetString("Extensions_Streams_StreamExtensions_WriteToString_CanRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}.CanWrite&quot; must be true..
        /// </summary>
        internal static string Extensions_Strings_StringExtensions_ToStream_CanWrite {
            get {
                return ResourceManager.GetString("Extensions_Strings_StringExtensions_ToStream_CanWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must inherit from IEnumerable..
        /// </summary>
        internal static string Extensions_Types_TypeExtensions_GetElementType {
            get {
                return ResourceManager.GetString("Extensions_Types_TypeExtensions_GetElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; is not a valid type..
        /// </summary>
        internal static string Reflection_ReflectionHelper_ConstructObject {
            get {
                return ResourceManager.GetString("Reflection_ReflectionHelper_ConstructObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be equal..
        /// </summary>
        internal static string Validation_Argument_Assert_AreEqual {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_AreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must not be equal to the specified invalid value..
        /// </summary>
        internal static string Validation_Argument_Assert_AreNotEqual {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_AreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must not be reference equal to the specified invalid value..
        /// </summary>
        internal static string Validation_Argument_Assert_AreNotReferenceEqual {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_AreNotReferenceEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be reference equal..
        /// </summary>
        internal static string Validation_Argument_Assert_AreReferenceEqual {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_AreReferenceEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must end with the specified value..
        /// </summary>
        internal static string Validation_Argument_Assert_EndsWith {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must have the specified attribute..
        /// </summary>
        internal static string Validation_Argument_Assert_HasAttribute {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_HasAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be an assignable type..
        /// </summary>
        internal static string Validation_Argument_Assert_IsAssignable {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_IsAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be false..
        /// </summary>
        internal static string Validation_Argument_Assert_IsFalse {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be within the specified range..
        /// </summary>
        internal static string Validation_Argument_Assert_IsInRange {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_IsInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be less than or equal to the specified maximum..
        /// </summary>
        internal static string Validation_Argument_Assert_IsMaximum {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_IsMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be greater than or equal to the specified minimum..
        /// </summary>
        internal static string Validation_Argument_Assert_IsMinimum {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_IsMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must not be null..
        /// </summary>
        internal static string Validation_Argument_Assert_IsNotNull {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must not be null or empty..
        /// </summary>
        internal static string Validation_Argument_Assert_IsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_IsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must not be null or empty..
        /// </summary>
        internal static string Validation_Argument_Assert_IsNotNullOrEmpty_Collection {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_IsNotNullOrEmpty_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must not be null, empty or whitespace..
        /// </summary>
        internal static string Validation_Argument_Assert_IsNotNullOrWhitespace {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_IsNotNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be null..
        /// </summary>
        internal static string Validation_Argument_Assert_IsNull {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be true..
        /// </summary>
        internal static string Validation_Argument_Assert_IsTrue {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be of the specified type..
        /// </summary>
        internal static string Validation_Argument_Assert_IsType {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_IsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be a valid index position..
        /// </summary>
        internal static string Validation_Argument_Assert_IsValidIndexPosition {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_IsValidIndexPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must start with the specified value..
        /// </summary>
        internal static string Validation_Argument_Assert_StartsWith {
            get {
                return ResourceManager.GetString("Validation_Argument_Assert_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be a valid email..
        /// </summary>
        internal static string Validation_Argument_AssertFormat_IsEmail {
            get {
                return ResourceManager.GetString("Validation_Argument_AssertFormat_IsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be a valid postal code FSA..
        /// </summary>
        internal static string Validation_Argument_AssertFormat_IsFSA {
            get {
                return ResourceManager.GetString("Validation_Argument_AssertFormat_IsFSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be a valid postal code LDU..
        /// </summary>
        internal static string Validation_Argument_AssertFormat_IsLDU {
            get {
                return ResourceManager.GetString("Validation_Argument_AssertFormat_IsLDU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be a number..
        /// </summary>
        internal static string Validation_Argument_AssertFormat_IsNumber {
            get {
                return ResourceManager.GetString("Validation_Argument_AssertFormat_IsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be a valid postal code..
        /// </summary>
        internal static string Validation_Argument_AssertFormat_IsPostalCode {
            get {
                return ResourceManager.GetString("Validation_Argument_AssertFormat_IsPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be a valid URI..
        /// </summary>
        internal static string Validation_Argument_AssertFormat_IsUri {
            get {
                return ResourceManager.GetString("Validation_Argument_AssertFormat_IsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; must be a valid ZIP code..
        /// </summary>
        internal static string Validation_Argument_AssertFormat_IsZIPCode {
            get {
                return ResourceManager.GetString("Validation_Argument_AssertFormat_IsZIPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be equal..
        /// </summary>
        internal static string Validation_Property_Assert_AreEqual {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_AreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must not equal to the specified invalid value..
        /// </summary>
        internal static string Validation_Property_Assert_AreNotEqual {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_AreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must not be reference equal to the specified invalid value..
        /// </summary>
        internal static string Validation_Property_Assert_AreNotReferenceEqual {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_AreNotReferenceEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be reference equal..
        /// </summary>
        internal static string Validation_Property_Assert_AreReferenceEqual {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_AreReferenceEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must end with the specified value..
        /// </summary>
        internal static string Validation_Property_Assert_EndsWith {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must have the specified attribute..
        /// </summary>
        internal static string Validation_Property_Assert_HasAttribute {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_HasAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be an assignable type..
        /// </summary>
        internal static string Validation_Property_Assert_IsAssignable {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_IsAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be false..
        /// </summary>
        internal static string Validation_Property_Assert_IsFalse {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be within the specified range..
        /// </summary>
        internal static string Validation_Property_Assert_IsInRange {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_IsInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be less than or equal to the specified maximum..
        /// </summary>
        internal static string Validation_Property_Assert_IsMaximum {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_IsMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be greater than or equal to the specified minimum..
        /// </summary>
        internal static string Validation_Property_Assert_IsMinimum {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_IsMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must not be null..
        /// </summary>
        internal static string Validation_Property_Assert_IsNotNull {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must not be null or empty..
        /// </summary>
        internal static string Validation_Property_Assert_IsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_IsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must not be null or empty..
        /// </summary>
        internal static string Validation_Property_Assert_IsNotNullOrEmpty_Collection {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_IsNotNullOrEmpty_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must not be null, empty or whitespace..
        /// </summary>
        internal static string Validation_Property_Assert_IsNotNullOrWhitespace {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_IsNotNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be null..
        /// </summary>
        internal static string Validation_Property_Assert_IsNull {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be true..
        /// </summary>
        internal static string Validation_Property_Assert_IsTrue {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be of the specified type..
        /// </summary>
        internal static string Validation_Property_Assert_IsType {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_IsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be a valid index position..
        /// </summary>
        internal static string Validation_Property_Assert_IsValidIndexPosition {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_IsValidIndexPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must start with the specified value..
        /// </summary>
        internal static string Validation_Property_Assert_StartsWith {
            get {
                return ResourceManager.GetString("Validation_Property_Assert_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be a valid email..
        /// </summary>
        internal static string Validation_Property_AssertFormat_IsEmail {
            get {
                return ResourceManager.GetString("Validation_Property_AssertFormat_IsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be a valid postal code FSA..
        /// </summary>
        internal static string Validation_Property_AssertFormat_IsFSA {
            get {
                return ResourceManager.GetString("Validation_Property_AssertFormat_IsFSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be a valid postal code LDU..
        /// </summary>
        internal static string Validation_Property_AssertFormat_IsLDU {
            get {
                return ResourceManager.GetString("Validation_Property_AssertFormat_IsLDU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be a number..
        /// </summary>
        internal static string Validation_Property_AssertFormat_IsNumber {
            get {
                return ResourceManager.GetString("Validation_Property_AssertFormat_IsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be a valid postal code..
        /// </summary>
        internal static string Validation_Property_AssertFormat_IsPostalCode {
            get {
                return ResourceManager.GetString("Validation_Property_AssertFormat_IsPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be a valid URI..
        /// </summary>
        internal static string Validation_Property_AssertFormat_IsUri {
            get {
                return ResourceManager.GetString("Validation_Property_AssertFormat_IsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; must be a valid ZIP code..
        /// </summary>
        internal static string Validation_Property_AssertFormat_IsZIPCode {
            get {
                return ResourceManager.GetString("Validation_Property_AssertFormat_IsZIPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid email..
        /// </summary>
        internal static string Validation_Value_AssertFormat_IsEmail {
            get {
                return ResourceManager.GetString("Validation_Value_AssertFormat_IsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid postal code FSA..
        /// </summary>
        internal static string Validation_Value_AssertFormat_IsFSA {
            get {
                return ResourceManager.GetString("Validation_Value_AssertFormat_IsFSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid postal code LDU..
        /// </summary>
        internal static string Validation_Value_AssertFormat_IsLDU {
            get {
                return ResourceManager.GetString("Validation_Value_AssertFormat_IsLDU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value  must be a number..
        /// </summary>
        internal static string Validation_Value_AssertFormat_IsNumber {
            get {
                return ResourceManager.GetString("Validation_Value_AssertFormat_IsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid postal code..
        /// </summary>
        internal static string Validation_Value_AssertFormat_IsPostalCode {
            get {
                return ResourceManager.GetString("Validation_Value_AssertFormat_IsPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid URI..
        /// </summary>
        internal static string Validation_Value_AssertFormat_IsUri {
            get {
                return ResourceManager.GetString("Validation_Value_AssertFormat_IsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid ZIP code..
        /// </summary>
        internal static string Validation_Value_AssertFormat_IsZIPCode {
            get {
                return ResourceManager.GetString("Validation_Value_AssertFormat_IsZIPCode", resourceCulture);
            }
        }
    }
}
